### PR TITLE
update to fastify 3

### PR DESCRIPTION
**Pull request by wesselvdv**
This updates all dependencies and typings for fastify 3. Will mean a breaking change due to fastify 3 dropping support for node 8 & 9.

### CODE REVIEW

**Comment by Tarang11** [comment]
@wesselvdv, we can't remove support for fastify 2.

**Comment by wesselvdv** [comment]
How would you propose supporting fastify 3 then?

**Comment by Tarang11** [comment]
@wesselvdv, well i don't see any problem with new fastify version, pls mention any.

**Comment by wesselvdv** [comment]
The typings are incompatible, meaning that the newest typings don't have the same type arguments as the older ones.

**Comment by wesselvdv** [comment]
Seems to be no more issues aside from the req warning. Weird I though I was getting type issues from csrf as well.

**Pull request closed without merging**
